### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CaptainStabs**
Added additional requirements
The other "changes" are just a side effect of my stupidity.

### CODE REVIEW

**Comment by titu1994** [comment]
Thanks for the PR!

**Comment by CaptainStabs** [comment]
If you could take a look at my main branch, that'd be greatly appreciated! I'm stumped on this value error.
`
 File "C:\Users\stabs\Downloads\Image-Super-Resolution-master\models.py", line 646, in create_model
    x = MaxPooling2D((2, 2))(c2)
`
`
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool' (op: 'MaxPool') with input shapes: [?,196,1,128].
`

**Comment by titu1994** [comment]
Input image size is smaller than 2^(number of max pools), so after a certain point you are trying to pool a (1x1) image, and that gives a negative index.

**Comment by CaptainStabs** [comment]
> Input image size is smaller than 2^(number of max pools), so after a certain point you are trying to pool a (1x1) image, and that gives a negative index.

I know this is a dead project and that you probably have more important ones to work on, but I'm stumped as to how to fix this. It should be the last kink to work out before the next pull request.

**Comment by titu1994** [comment]
There was a flag somewhere which determine what scale the image to set to + the number of strides. You could set it such that 2^stride <= image width / image height. 

Sorry, I've quite forgotten the inner workings of this codebase

**Comment by titu1994** [comment]
Actually, the best advice I can give is to probably look into this - seems like a much more powerful method than the ones in this repo- https://niopeng.github.io/HyperRIM/

**Pull request merged**
